# Generated by Django 3.0.2 on 2020-01-31 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('addhar_card_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MissingPersonImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('pickel', models.TextField(blank=True, null=True)),
                ('addhar_card_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.MissingPerson')),
            ],
        ),
    ]
