# Generated by Django 2.1 on 2020-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='body_built',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='face_complexion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='face_shape',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='lower_height_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='upper_height_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
